In [1]:
['a', 'b', 'c'] + [1,2,3]

['a', 'b', 'c', 1, 2, 3]

In [1]:
import numpy as np
m = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10,11], [12,13,14,15,16,17], [18,19,20,21,22,23], [24,25,26,27,28,29], [30,31,32,33, 34,35]])
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
m[::7]

array([[0, 1, 2, 3, 4, 5]])

In [12]:
m.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [6]:
m[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [14]:
m[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [15]:
m[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [18]:

a = [4,2,3]
a.sort()
print (a)

[2, 3, 4]


In [19]:
a = 1
b = 2
c = a/b
print (c)

0.5
